# Generated by Django 5.2.5 on 2025-08-08 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("total_sessions", models.PositiveIntegerField(default=0)),
                ("successful_sessions", models.PositiveIntegerField(default=0)),
                ("failed_sessions", models.PositiveIntegerField(default=0)),
                ("regex_sessions", models.PositiveIntegerField(default=0)),
                ("llm_sessions", models.PositiveIntegerField(default=0)),
                ("total_resources_extracted", models.PositiveIntegerField(default=0)),
                ("total_files_processed", models.PositiveIntegerField(default=0)),
                ("total_file_size_mb", models.FloatField(default=0.0)),
                ("average_processing_time", models.FloatField(default=0.0)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="KRTSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("original_filename", models.CharField(max_length=255)),
                ("file_size", models.PositiveIntegerField()),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("regex", "Regex/Heuristics"),
                            ("llm", "Large Language Model"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("openai", "OpenAI (GPT)"),
                            ("anthropic", "Anthropic (Claude)"),
                            ("gemini", "Google (Gemini)"),
                            (
                                "openai_compatible",
                                "OpenAI-compatible (Ollama, DeepSeek, Grok)",
                            ),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("model_name", models.CharField(blank=True, max_length=100, null=True)),
                ("base_url", models.URLField(blank=True, null=True)),
                ("extra_instructions", models.TextField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=500, null=True)),
                ("abstract", models.TextField(blank=True, null=True)),
                ("krt_data", models.JSONField(default=list)),
                ("processing_time", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="processing",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("resources_found", models.PositiveIntegerField(default=0)),
                ("new_resources", models.PositiveIntegerField(default=0)),
                ("reused_resources", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["session_id"], name="web_krtsess_session_0579bd_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="web_krtsess_created_f6a21a_idx"
                    ),
                    models.Index(
                        fields=["status"], name="web_krtsess_status_f18dd5_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="KRTExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("json", "JSON"),
                            ("csv", "CSV"),
                            ("excel", "Excel (XLSX)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("exported_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to="web.krtsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-exported_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcessedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="temp_uploads/%Y/%m/%d/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="web.krtsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
