# Generated by Django 4.2.16 on 2025-08-08 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="krtsession",
            name="authors",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="krtsession",
            name="biorxiv_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="krtsession",
            name="categories",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="krtsession",
            name="doi",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="krtsession",
            name="epmc_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="krtsession",
            name="existing_krt_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="krtsession",
            name="existing_krt_data",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="krtsession",
            name="existing_krt_detected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="krtsession",
            name="input_method",
            field=models.CharField(
                choices=[("upload", "File Upload"), ("url", "bioRxiv URL/DOI")],
                default="upload",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="krtsession",
            name="journal",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="krtsession",
            name="keywords",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="krtsession",
            name="publication_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doi",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "filename_hash",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True, unique=True
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=500, null=True)),
                ("authors", models.TextField(blank=True, null=True)),
                ("abstract", models.TextField(blank=True, null=True)),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("journal", models.CharField(blank=True, max_length=255, null=True)),
                ("keywords", models.TextField(blank=True, null=True)),
                ("first_processed", models.DateTimeField(auto_now_add=True)),
                ("last_processed", models.DateTimeField(auto_now=True)),
                ("total_sessions", models.PositiveIntegerField(default=0)),
                ("has_existing_krt", models.BooleanField(default=False)),
                ("existing_krt_count", models.PositiveIntegerField(default=0)),
                ("existing_krt_data", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["-last_processed"],
                "indexes": [
                    models.Index(fields=["doi"], name="web_article_doi_adb945_idx"),
                    models.Index(
                        fields=["filename_hash"], name="web_article_filenam_cdafe7_idx"
                    ),
                    models.Index(
                        fields=["last_processed"], name="web_article_last_pr_7bd92f_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="krtsession",
            name="article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="web.article",
            ),
        ),
    ]
