# Generated by Django 4.2.16 on 2025-08-08 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_krtsession_authors_krtsession_biorxiv_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="XMLFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doi", models.CharField(db_index=True, max_length=255, unique=True)),
                (
                    "epmc_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                ("file_path", models.CharField(max_length=500)),
                ("file_size", models.PositiveIntegerField()),
                ("file_hash", models.CharField(db_index=True, max_length=64)),
                ("downloaded_at", models.DateTimeField(auto_now_add=True)),
                ("last_checked", models.DateTimeField(auto_now=True)),
                (
                    "download_source",
                    models.CharField(default="europe_pmc", max_length=50),
                ),
                ("title", models.CharField(blank=True, max_length=500, null=True)),
                ("authors", models.TextField(blank=True, null=True)),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("journal", models.CharField(default="bioRxiv", max_length=255)),
                ("is_available", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-downloaded_at"],
                "indexes": [
                    models.Index(fields=["doi"], name="web_xmlfile_doi_9de6ec_idx"),
                    models.Index(
                        fields=["epmc_id"], name="web_xmlfile_epmc_id_e6a057_idx"
                    ),
                    models.Index(
                        fields=["publication_date"],
                        name="web_xmlfile_publica_3c999f_idx",
                    ),
                    models.Index(
                        fields=["is_available"], name="web_xmlfile_is_avai_423d51_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="article",
            name="xml_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="web.xmlfile",
            ),
        ),
    ]
